name: app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.4"


dependencies:
  flutter:
    sdk: flutter
  provider:
   


  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.8
  google_maps_flutter_web: ^0.4.0
  sqflite: ^2.0.2+1
  path_provider: ^2.0.11
  path: ^1.8.1
  latlng: ^0.1.0
  geolocator: ^8.2.1
  url_launcher: ^6.1.4
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  flutterfire_ui: ^0.4.3+20
  cloud_firestore: ^4.1.0
  
 

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

  
  assets:
   - images/R.jpg
  

  